version: "2"

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
issues:
  exclude-files:
    - ".*_test\\.go"

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 3m
