version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - all

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 3m
